// Generated by scripts/write-env.js - do not commit to VCS
// Provides runtime env for client-side code
window.SUPABASE_URL = "https://ltxvnsqiufatmtkmrwga.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0eHZuc3FpdWZhdG10a21yd2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMzkwNjcsImV4cCI6MjA3NzgxNTA2N30.s5kfaQDFQP6GrjIgwB4B4CnG2pDDqMdApfzVrS4xrXg";
