// write-env.js
// Writes js/env.js from environment variables at build time.
// Vercel: add SUPABASE_URL and SUPABASE_ANON_KEY in Project > Settings > Environment Variables

const fs = require('fs');
const path = require('path');
require('dotenv').config();

const outPath = path.join(__dirname, '..', 'js', 'env.js');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

const content = `// Generated by scripts/write-env.js - do not commit to VCS
// Provides runtime env for client-side code
window.SUPABASE_URL = ${JSON.stringify(supabaseUrl)};
window.SUPABASE_ANON_KEY = ${JSON.stringify(supabaseAnonKey)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);
